apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: default
  labels:
    app: portfolio-webapi
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PortfolioEnterpriseDb;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;Encrypt=False"
  ConnectionStrings__Redis: "redis:6379"
  Jwt__Secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS_LONG_12345"
  Jwt__Issuer: "PortfolioEnterpriseAPI"
  Jwt__Audience: "PortfolioEnterpriseClient"
  Email__Username: "apikey"
  Email__Password: "CHANGE_ME"
  Hangfire__ConnectionString: "Server=sqlserver;Database=PortfolioHangfire;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;Encrypt=False"
